### ISSUE TITLE
Editing lyrics induces a crash

### ISSUE THREAD

**Issue by Syntax-Err5** [25huizengek1/ViMusic#49] opened 2023-12-23 00:24 UTC
### Steps to reproduce the bug

1. Play a song
2. Open lyrics
3. Press the three dots
4. Press "edit lyrics" 

### Expected behavior

The lyrics editor pop-up should appear

### Actual behavior

The app crashes

### Logs

FATAL EXCEPTION: main
Process: it.vfsfitvnm.vimusic, PID: 31398
java.lang.ArrayIndexOutOfBoundsException: length=20480; index=-1
	at M3.c.x(SourceFile:5)
	at E.r.l0(SourceFile:19)
	at E.r.g(SourceFile:11)
	at a4.h.p(SourceFile:248)
	at M.d.p(SourceFile:54)
	at F0.c.a(SourceFile:111)
	at F0.c.p(SourceFile:40)
	at M.d.p(SourceFile:54)
	at F4.i.j(SourceFile:193)
	at F0.c.a(SourceFile:83)
	at F0.c.p(SourceFile:28)
	at M.d.p(SourceFile:54)
	at F0.o.a(SourceFile:22)
	at m.j.a(SourceFile:272)
	at m.j.p(SourceFile:269)
	at M.d.p(SourceFile:54)
	at L4.r.b(SourceFile:152)
	at androidx.compose.ui.platform.q0.a(SourceFile:366)
	at u.j.a(SourceFile:1232)
	at u.j.p(SourceFile:52)
	at M.d.p(SourceFile:54)
	at L4.r.b(SourceFile:152)
	at androidx.compose.ui.platform.X.a(SourceFile:495)
	at androidx.compose.ui.platform.u1.a(SourceFile:171)
	at androidx.compose.ui.platform.u1.p(SourceFile:28)
	at M.d.p(SourceFile:54)
	at L4.r.a(SourceFile:220)
	at androidx.compose.ui.platform.u1.a(SourceFile:145)
	at androidx.compose.ui.platform.u1.p(SourceFile:16)
	at M.d.p(SourceFile:54)
	at r4.r.i0(SourceFile:15)
	at E.r.r(SourceFile:118)
	at E.r.k(SourceFile:11)
	at E.y.o(SourceFile:34)
	at E.J0.a(SourceFile:35)
	at E.p.a(SourceFile:5)
	at E.p.a(SourceFile:5)
	at E.y.p(SourceFile:9)
	at E.y.k(SourceFile:3)
	at androidx.compose.ui.platform.v1.c(SourceFile:100)
	at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(SourceFile:7)
	at androidx.compose.ui.platform.WrappedComposition.k(SourceFile:9)
	at androidx.compose.ui.platform.WrappedComposition.e(SourceFile:1)
	at androidx.lifecycle.v.a(SourceFile:23)
	at androidx.lifecycle.w.a(SourceFile:216)
	at androidx.compose.ui.platform.v1.c(SourceFile:68)
	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(SourceFile:109)
	at android.view.View.dispatchAttachedToWindow(View.java:21475)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3540)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3547)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3547)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3547)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3547)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2957)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:420)
	at android.view.Choreographer.doFrame(Choreographer.java:900)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### ViMusic version

0.6.0

### Android version

ColorOS 13, based on Android 13

**Comment by 25huizengek1** [comment] 2023-12-23 00:26
Duplicate of #47 (caused by compose foundation upgrade)

**Closed by 25huizengek1** 2023-12-23 00:26 UTC
Labels: bug

**Comment by Syntax-Err5** [comment] 2023-12-23 00:32
Ah I see, thanks!
