### ISSUE TITLE
Song position doesn't get saved

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#126] opened 2024-02-22 05:35 UTC
### Steps to reproduce the bug

NOTE:This works best with 2 or more songs
1. Add a song
2. Remove the song
3. Add that same song again 

### Expected behavior

1. The song position should be saved and it should be restored to that same position the next time you add the song

### Actual behavior

The song gets added to the top of the library like it has never been added before. This might not count as a bug but it sure feels like one, coming from the classic vimusic app~ when you hide/remove songs the position gets saved to the database and it would be restored to that same position when next you add that song. 

### ViMusic version

v0.6.4

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 10

### Device info

I'm using Tecno spark go (2021), running HiOS

### Additional information

Another issue similar to this:
In the classic vimusic app, whenever you add any song, even if you remove/hide it, searching in the library tab (offline search), the song still shows up even though it won't play. Again, this does not feel like a bug, but to me it's one. In v0.6.4 when you remove songs it's gone for good.
 This feature is actually helpful to add songs in the same order that they were added initially, I personally like my songs playing in a specific order so even when I remove one of them I'd like it to be restored to it's initial position when next I add it.

 secondly I find it easier to do an offline search for a song I've listened to before and add the song from there than using online search, 

For context, all the other songs I've added from the classic vimusic app still shows up in the database (and offline search) even though they are not cached and I'm not listening to them. Even some songs get added by default from playlist/album/queue even though they aren't cached. 

So I don't know what went wrong but I'd like the app to save song position and save it offline too so that next time I do an offline search I can see it and it will be restored to it's original position instead of the top of the library.

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [ ] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment] 2024-02-23 16:40
There is no reason to save song position: that is what playlists are made for, and the Songs tab can be sorted in three different ways, and purely for simplicity's sake I want to keep it this way. If you really want to keep your original order from ViMusic, you could probably just export all songs in your library to a separate playlist...

**Comment by 25huizengek1** [comment] 2024-02-23 16:40
Closing, because this is not a bug.

**Closed by 25huizengek1** 2024-02-23 16:40 UTC
Labels: bug
