### ISSUE TITLE
Create new playback lists does not work

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#48] opened 2023-12-22 08:48 UTC
### Steps to reproduce the bug

01. Start the app, 
02. try to create a new playlist
03. and the app crashes

### Expected behavior

The error has been fixed since the last update

### Actual behavior

.

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/103368536/a9b130f0-4125-401a-8b93-ddf78ffc99cf

### ViMusic version

0.6.0

### Android version

Android 12

**Comment by 25huizengek1** [comment] 2023-12-22 09:20
Duplicate of #47, I'm very sorry this happened, but it's not caused by my code.

**Closed** 2023-12-22 09:20 UTC
Labels: bug

**Comment by siggi1984** [comment] 2023-12-22 17:03
> Duplicate of #47, I'm very sorry this happened, but it's not caused by my code.

But the error was not there before.

**Comment by 25huizengek1** [comment] 2023-12-22 18:15
I know, please read #47
