### ISSUE TITLE
Playlist: Show download status of playlists

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViMusic#112] opened 2024-02-13 03:26 UTC
## Feature request: Show download status of playlists

When a playlist is downloaded, there's no clear indication whether the playlist has been downloaded or not. The download button remains the same as it was before downloading the playlist, lacking a differentiation from the playlist which has not been downloaded.

Reference screenshot:
> ![Screenshot_20240213-085106~2](https://github.com/25huizengek1/ViMusic/assets/87353286/7c326c1e-e002-4ede-87a4-bee2865ba894)

**Comment by 25huizengek1** [comment] 2024-02-13 11:20
Duplicate of #114

**Closed by 25huizengek1** 2024-02-13 11:20 UTC
Labels: duplicate, enhancement
