### ISSUE TITLE
Playlist not loading in Home screen + when we search 

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViMusic#118] opened 2024-02-18 12:07 UTC
# Playlist not loading in Quick Picks 

![Screenshot_20240218-173424_ViMusic.png](https://github.com/25huizengek1/ViMusic/assets/151006009/1c79e30b-f885-4840-be67-80eec53f688e)

# songs and Music videos not showing completely

![Screenshot_20240218-173636_ViMusic.png](https://github.com/25huizengek1/ViMusic/assets/151006009/48968653-e3ae-4fc5-9efd-a504404b1355)

![Screenshot_20240218-173642_ViMusic.png](https://github.com/25huizengek1/ViMusic/assets/151006009/5d431740-1c6e-404f-99d1-bc70c6a7bdfd)

@25huizengek1

**Comment by dtomvan** [comment] 2024-02-18 14:06
Duplicate of #115, let's move the discussion there

**Comment by 25huizengek1** [comment] 2024-02-18 18:35
To explain/respond to this:

First screenshot: intended behavior: when suggestions are not available they do not get shown.
Second screenshot: duplicate of #115

**Closed by 25huizengek1** 2024-02-18 18:35 UTC
