### ISSUE TITLE
Add undo snackbar

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#96] opened 2024-01-27 19:55 UTC
It has often happened to me that I have accidentally swiped to the left in the song area and removed a song. Maybe you could add a notification that the song has been removed, as well as an option to undo the action.

**Comment by 25huizengek1** [comment] 2024-01-27 22:20
Duplicate of #69

**Closed by 25huizengek1** 2024-01-27 22:20 UTC
Labels: duplicate, enhancement

**Comment by siggi1984** [comment] 2024-01-28 11:43
> Duplicate of #69

Oh sorry, I overlooked that.
