### ISSUE TITLE
Can't sync playlists or add new playlists (Edit: It seems my ViMusic isn't connecting to youtube)

### ISSUE THREAD

**Issue by divno** [25huizengek1/ViMusic#90] opened 2024-01-24 22:36 UTC
### Steps to reproduce the bug

If you have a playlist already saved just press sync, and if you added new songs it should sync. But with this version it doesn't 
I
If you dont have a playlist added just copy any playlist link from youtube and try saving it, it blocks that aswell

### Expected behavior

The songs should sync and update with the playlist when the sync button is pressed

### Actual behavior

Nothing happens

### ViMusic version

 v0.6.3

### Android version

Android 14

**Comment by 25huizengek1** [comment] 2024-01-24 22:52
Can't reproduce any bug with this, the playlists get synchronized perfectly fine for me. Can you please provide clear steps on how you reproduce this (with the exact kind of changes made to the playlist) and with what playlist this happens?

Secondly, though I'm not sure if you meant this: you can just search for a playlist or share it with ViMusic. There is no box to paste the playlist link into as of right now.

**Comment by divno** [comment] 2024-01-25 00:59
So with the playlists I have saved I press the 3 dots in the upper right
and then press sync at the bottom where it pops up. This problem happens on
all playlists and I can't even search for playlists. Only changes made to
playlists are added or removed songs, I havent changed the sorting of songs.

Upon further investigation I found that I can't search for anything, its as
if the app isn't connected to the internet, the only thing that works is
already offline music and the quick picks section.

Oh I never knew you could share straight to ViMusic, but the way I used to
do it is copy the link of a playlist and paste it in the search bar of
ViMusic and it shows an option to view playlist.

**Comment by divno** [comment] 2024-01-25 01:21
I'd be happy to send logs but I'm unsure what app to use to extract them

**Comment by 25huizengek1** [comment] 2024-01-27 16:52
I just want to ask you though: in what country do you live/browse from? You do not have to answer, but please check if YouTube Music is available in your country: https://support.google.com/youtubemusic/answer/6313540?hl=en

**Comment by divno** [comment] 2024-01-27 17:08
I live in the US so it should work but its strange, the quick picks section
works perfectly fine though.

I'll make to sure to collect logs for vimusic for you.

**Comment by divno** [comment] 2024-01-27 18:09
I am trying to use a terminal app on my phone to access adb logcat but I
can't get it to work and I don't have a computer making things more
difficult.

I know this isn't your job but do you know what to do to make it work?
I cant find instructions on how to do it through the terminal on the phone

**Comment by 25huizengek1** [comment] 2024-01-27 22:45
> I live in the US so it should work but its strange, the quick picks section works perfectly fine though. I'll make to sure to collect logs for vimusic for you.

Really weird, no clue why this could happen.

> I am trying to use a terminal app on my phone to access adb logcat but I
can't get it to work and I don't have a computer making things more
difficult.

A terminal app has no access to adb (unless you have rooted your device, of course), so what I'd recommend in this case, is that you install [Shizuku](https://shizuku.rikka.app/), a privileged system service that can grant adb access to apps, in combination with [LogFox](https://github.com/F0x1d/LogFox), a simple logger app. You can start Shizuku (no pc or root required) first, then start LogFox in Shizuku mode (so you'll have access to ViMusic's logs) and filter for logs from ViMusic. You can make a recording of your logs, so start recording, go back to ViMusic, reproduce the issue, go back and stop the recording.

**Comment by divno** [comment] 2024-01-28 00:53
Thank you so much! I took two recordings one of them i played an offline song that worked properly, in case thats helpful to you and I also added a screen recording (I probably should have added this earlier)

https://photos.app.goo.gl/PRFVzWb4wQAAa1VG6

[27_01-19-37-01_413.log](https://github.com/25huizengek1/ViMusic/files/14074440/27_01-19-37-01_413.log)
[27_01-19-39-04_900.log](https://github.com/25huizengek1/ViMusic/files/14074441/27_01-19-39-04_900.log)

**Comment by dtomvan** [comment] 2024-02-05 09:38
Could this be the culprit:

<details>
<summary>Exerpt of the logs</summary>
```log

1706402255.401 10524 30757 30757 W System.err: V2.d: Client request(POST https://music.youtube.com/youtubei/v1/search) invalid: 400 . Text: "{
1706402255.401 10524 30757 30757 W System.err:   "error": {
1706402255.401 10524 30757 30757 W System.err:     "code": 400,
1706402255.401 10524 30757 30757 W System.err:     "message": "Request contains an invalid argument.",
1706402255.401 10524 30757 30757 W System.err:     "errors": [
1706402255.401 10524 30757 30757 W System.err:       {
1706402255.401 10524 30757 30757 W System.err:         "message": "Request contains an invalid argument.",
1706402255.401 10524 30757 30757 W System.err:         "domain": "global",
1706402255.401 10524 30757 30757 W System.err:         "reason": "badRequest"
1706402255.401 10524 30757 30757 W System.err:       }
1706402255.401 10524 30757 30757 W System.err:     ],
1706402255.401 10524 30757 30757 W System.err:     "status": "INVALID_ARGUMENT"
1706402255.401 10524 30757 30757 W System.err:   }
1706402255.401 10524 30757 30757 W System.err: }
1706402255.401 10524 30757 30757 W System.err: "
1706402255.401 10524 30757 30757 W System.err: 	at V2.j.s(SourceFile:243)
1706402255.401 10524 30757 30757 W System.err: 	at y4.a.o(SourceFile:9)
1706402255.401 10524 30757 30757 W System.err: 	at S4.J.run(SourceFile:95)
1706402255.401 10524 30757 30757 W System.err: 	at e2.D.run(SourceFile:28)
1706402255.401 10524 30757 30757 W System.err: 	at Y4.j.run(SourceFile:3)
1706402255.401 10524 30757 30757 W System.err: 	at Y4.a.run(SourceFile:96)

```

</details>

Lets hope @25huizengek1 has mappings for this version for further debugging.

**Comment by divno** [comment] 2024-02-05 11:52
Yes it looks like thats the issue, i dont know why it reported everything on my phone even if I requested ViMusic only.

**Comment by 25huizengek1** [comment] 2024-02-05 12:15
I'm sorry, I haven't seen that you posted logs. Thank you @dtomvan. This is on the release build, right?

**Comment by divno** [comment] 2024-02-05 13:08
Yes for the latest version

**Comment by 25huizengek1** [comment] 2024-02-06 00:02
There are not particularly much 'arguments' in a search request: context (as usual in all requests), plain query, 'params' (in this case filter parameter), and the mask. While upgrading to the new Innertube version, though, I updated the 'params', so these values should be valid. The only thing that comes to mind is the fact that the mask is never used anymore on YouTube, so my best bet is that this mask gets rejected by the server. This still doesn't explain the fact that it works on my device though...

**Comment by divno** [comment] 2024-02-06 02:28
I downgraded to 6.2 for the time being, I could get you logs from this version for comparison if you'd like. If you aren't able to fix this since it is a weird edge case don't worry, I'm just glad I get to benefit from ViMusic.👾

**Comment by divno** [comment] 2024-02-10 17:11
Unfortunately the update didn't fix the playlist updating issue but it did manage to fix the infinite loading for searches

**Comment by 25huizengek1** [comment] 2024-02-11 23:15
The newest update is v0.6.4, could you please try using that release, then get back with me with logs on this issue?

**Comment by divno** [comment] 2024-02-12 00:51
> Unfortunately the 0.6.2 update 
Meant 0.6.4 here and the infinite searches unfortunately happened again

0.6.2 Recordings (playlist sync tested and working):
[ViMusic_0.6.2_rec1.log](https://github.com/25huizengek1/ViMusic/files/14234612/ViMusic_0.6.2_rec1.log)
[ViMusic_0.6.2_rec2.log](https://github.com/25huizengek1/ViMusic/files/14234611/ViMusic_0.6.2_rec2.log)

0.6.4 Recordings (playlist sync and search tested [both don't work]):
[ViMusic_0.6.4_rec1.log](https://github.com/25huizengek1/ViMusic/files/14234616/ViMusic_0.6.4_rec1.log)
[ViMusic_0.6.4_rec2.log](https://github.com/25huizengek1/ViMusic/files/14234617/ViMusic_0.6.4_rec2.log)

**Comment by jojobozo** [comment] 2024-02-13 07:13
Same issue here, I live in France by the way

**Comment by 25huizengek1** [comment] 2024-02-13 11:25
This could be because of the fact that Android makes a distinction between for example `fr-FR` and `fr-rFR`, so probably YouTube just doesn’t recognize this and returns said error. I’ll analyze your logs later on @divno

**Comment by 25huizengek1** [comment] 2024-02-27 00:32
More evidence of this issue occurring:

![Screenshot_20240227-050306_ViMusic](https://github.com/25huizengek1/ViMusic/assets/151006009/04208361-2ca3-4354-9613-17a67171b4e3)
![Screenshot_20240227-050329_ViMusic](https://github.com/25huizengek1/ViMusic/assets/151006009/c9780b7f-b9ba-4dc6-8f94-b52c3e6e95da)
[27_02-05-16-03_639.log](https://github.com/25huizengek1/ViMusic/files/14412512/27_02-05-16-03_639.log)

```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by walker-11** [comment] 2024-02-27 00:37
You need mor logs?

**Comment by 25huizengek1** [comment] 2024-02-27 01:04
Apparently this had to do something with the device's language settings: I've added a fallback to English for all languages that YouTube doesn't (seem to) support. This should have fixed it, please let me know if this did the trick @divno @walker-11

**Comment by walker-11** [comment] 2024-02-27 01:10
> Apparently this had to do something with the device's language settings: I've added a fallback to English for all languages that YouTube doesn't (seem to) support. This should have fixed it, please let me know if this did the trick @divno @walker-11

I don't understand what you mean,!!?

**Comment by walker-11** [comment] 2024-02-27 01:11
> I just want to ask you though: in what country do you live/browse from? You do not have to answer, but please check if YouTube Music is available in your country: https://support.google.com/youtubemusic/answer/6313540?hl=en

I live in India Both YouTube and YouTube music available in my country

**Comment by divno** [comment] 2024-02-27 13:37
> Apparently this had to do something with the device's language settings: I've added a fallback to English for all languages that YouTube doesn't (seem to) support. This should have fixed it, please let me know if this did the trick @divno @walker-11

Unfortunately this version didn't fix it either

**Comment by 25huizengek1** [comment] 2024-02-27 15:01
Because there is no version that includes the fix? What build are you using @divno

**Comment by 25huizengek1** [comment] 2024-02-27 21:32
v0.6.5 was released before I implemented this fix. In about 45 minutes another nightly build will start though, so I'll link it here as soon as it's ready.

**Comment by 25huizengek1** [comment] 2024-02-27 23:46
https://github.com/25huizengek1/fdroid-repo/raw/81a9fcac2554e47c364ee6116980f5a947bf5bdc/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240228.apk

Or add [the F-Droid repository](https://25huizengek1.github.io/fdroid-repo/fdroid/repo/?fingerprint=A9F4730F35858B40CD7ED86E46030644120FB5DFBC1B3366D05CE38A7BDB5C79)

**Comment by divno** [comment] 2024-02-28 01:37
> v0.6.5 was released before I implemented this fix. In about 45 minutes another nightly build will start though, so I'll link it here as soon as it's ready.

Ahh ok thank you!

**Comment by divno** [comment] 2024-02-28 01:41
> https://github.com/25huizengek1/fdroid-repo/raw/81a9fcac2554e47c364ee6116980f5a947bf5bdc/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240228.apk
> 
> Or add [the F-Droid repository](https://25huizengek1.github.io/fdroid-repo/fdroid/repo/?fingerprint=A9F4730F35858B40CD7ED86E46030644120FB5DFBC1B3366D05CE38A7BDB5C79)

Thank you so much! It works flawlessly, everything works as expected! I also appreciate the integration of material you.

**Comment by walker-11** [comment] 2024-02-28 03:50
> https://github.com/25huizengek1/fdroid-repo/raw/81a9fcac2554e47c364ee6116980f5a947bf5bdc/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240228.apk
> 
> Or add [the F-Droid repository](https://25huizengek1.github.io/fdroid-repo/fdroid/repo/?fingerprint=A9F4730F35858B40CD7ED86E46030644120FB5DFBC1B3366D05CE38A7BDB5C79)

Wow this build Fixed the issue, what you added to fix that bug can I know?

**Comment by 25huizengek1** [comment] 2024-02-28 07:37
@walker-11 Look at 8605b349917277e6fdd6cc672014ef0c4dbf8eb8
YouTube doesn't return anything when the language code is not supported by them, so this tries to fall back to English when your exact language code is not supported. Maybe I should add a language picker for the YouTube API at some point, but at least this bug is fixed.

**Comment by 25huizengek1** [comment] 2024-02-28 07:38
> Thank you so much! It works flawlessly, everything works as expected! I also appreciate the integration of material you.

Nice, thank you for your appreciation! Closing as resolved.

**Closed by 25huizengek1** 2024-02-28 07:38 UTC
Labels: bug

**Comment by walker-11** [comment] 2024-03-01 16:20
Bro, in that nightly release build, songs stops playing in background i disabled battery optimisation also turned on that setting in Vi music, but it keeps stops in background, and it not happens with 0.6.2 build

**Comment by 25huizengek1** [comment] 2024-03-01 20:19
> Bro, in that nightly release build, songs stops playing in background i disabled battery optimisation also turned on that setting in Vi music, but it keeps stops in background, and it not happens with 0.6.2 build 

@walker-11 This is not related to this issue. Please fill out a separate issue form for this problem, in that way I can investigate this further. Please make sure your manufacturer doesn't have additional functionality enabled for pausing the player or killing the app.
