### ISSUE TITLE
Playlist item order is not saved

### ISSUE THREAD

**Issue by ardumiguel** [25huizengek1/ViMusic#68] opened 2024-01-11 15:21 UTC
### Steps to reproduce the bug

So, as the title says, when you try to change song order inside a playlist the change doesn't appear to take effect. In fact it automatically reverts to previous state. 

You can easily see it on video. I change order but as soon as I click it changes and the song I click is not the one that I listen.

### Expected behavior

Correct rearrangement of songs.

### Actual behavior

Already described

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/133792399/d864b13c-7077-455a-977c-cd78df7fb589

### ViMusic version

Latest

### Android version

Android 14

### Additional information

App is really good. Definitely an improvement from (discontinued?) Original ViMusic. Minor lags found. Other minor bugs were found too.

**Comment by 25huizengek1** [comment] 2024-01-11 22:09
Can't reproduce (playlist with 3 songs). It seems like the reordering never finishes, as the FAB doesn't animate back into the screen. In your recording at 0:18 you can see the glitchy (?), but successful finished reordering animation of 'Unholy'. That is how it's supposed to behave.

In order to investigate further: what do you mean with 'Latest'? The latest release build (v0.6.2) or the latest nightly build (v0.6.2 / 20240110)? I can't reproduce on either versions.

**Comment by ardumiguel** [comment] 2024-01-11 22:20
Yes, I'm using the latest release from "releases" page. 
And yes it's like if the reordering never happened. What do you mean by "FAB"?

By the way, is there any email address I can use to contact you? I'd really like to give you feedback and possibly coding help😉 17yo too.

**Comment by ardumiguel** [comment] 2024-01-11 22:26
Yes, I'm using the latest release from "releases" page. 
And yes it's like if the reordering never happened. What do you mean by "FAB"?

By the way, is there any email address I can use to contact you? I'd really like to give you feedback and possibly coding help😉 17yo too.

**Comment by 25huizengek1** [comment] 2024-01-11 22:32
Thank you. I'll look into this when I have the time to. I am aware that the reordering is sometimes buggy. Previously this worked using a certain amount of out-of-bounds items in the lazy list (but that API is now internal) and the animateItemPlacement Modifier, but that caused some issues in newer versions of foundation, so I decided to move away from it.

FAB stands for floating action button, in this case the shuffle button at the bottom of the screen.

You can contact me through development@vitune.app. And of course you can always open an issue or pull request.

**Comment by ardumiguel** [comment] 2024-01-12 06:46
Yo keep on going with the follow-up, I have to add that I couldn't also reproduce the bug this time on an Android 13 tablet, Samsung.

**Comment by genericbetatester** [comment] 2024-01-12 11:10
There's a bug that is a bit similar to this on my device too, only that it happens when rearranging songs on the "now playing" queue

https://github.com/25huizengek1/ViMusic/assets/140274753/042540a0-069d-41d1-86cc-faed5244bb2f

**Comment by genericbetatester** [comment] 2024-01-12 11:14
There's a bug that is a bit similar to this on my device too, only that it happens when rearranging songs on the "now playing" queue

https://github.com/25huizengek1/ViMusic/assets/140274753/f74cc4f7-3fb8-47a0-bfeb-846b24d88683

**Comment by 25huizengek1** [comment] 2024-01-13 22:06
To respond to this recording:

1. I'm aware of the now playing animation, and have already improved it a little bit, but decided it looks good enough and moved on. I think in order to fix this we can just add a delay before the actual animation happens?
2. I'm aware of the empty space showing. This happens when the item you're currently dragging gets out of the viewport, as described [here](https://github.com/25huizengek1/ViMusic/issues/68#issuecomment-1888074538)

**Comment by genericbetatester** [comment] 2024-01-14 10:08
> To respond to this recording:
> 
> 1. I'm aware of the now playing animation, and have already improved it a little bit, but decided it looks good enough and moved on. I think in order to fix this we can just add a delay before the actual animation happens?
> 2. I'm aware of the empty space showing. This happens when the item you're currently dragging gets out of the viewport, as described [here](https://github.com/25huizengek1/ViMusic/issues/68#issuecomment-1888074538)

1.Delaying the animation sounds like a good idea

2. It's a minor issue I can wait till it's fixed

**Comment by 25huizengek1** [comment] 2024-01-18 19:10
I'll mark this as wontfix for now as I can't fix this without reflection (which is inefficient and error-prone)

**Comment by ardumiguel** [comment] 2024-01-21 21:49
So there isn't a fix for this?

**Comment by 25huizengek1** [comment] 2024-01-23 13:28
Well, there is, but it involves reflection, which I want to avoid for now. I think the AndroidX team will fix this at some point, but I'm not sure when.

I do think I can add the animations in the list back, though, as [this has been fixed](https://android.googlesource.com/platform/frameworks/support/+/14a894f3270c310a12a68f7ae1d0eda2ffe1c81e).

Google is tracking this is various issues. It seems like they first went for an approach with 'beyondBoundsItemCount', but now the new `LookaheadScope` seems promising. I'll try to figure something out.

**Comment by 25huizengek1** [comment] 2024-01-24 09:05
I decided to look at Google's commit history (because there are little to no docs about this) and reasoning behind this change. It actually makes some sense and I cooked up a fix. It requires some more testing, though, but it will fix all problems with the reordering. I fixed all issues (visual glitches persistence, animations) for playlists and the queue.

Will try to push a fix in a few hours when I have the time to. Thank you for your patience.

**Comment by 25huizengek1** [comment] 2024-01-24 09:19
To add some more context to this: this issue turned out to be caused by both API changes in Foundation and a case in the SQLite codegen that caused the query to load unordered data, so even when the reordering did come through it still wouldn't be reflected in the UI. I fixed both issues, so we should have consistent behavior again.

**Comment by 25huizengek1** [comment] 2024-01-24 09:22
And for @genericbetatester and the people that are also experiencing this issue: the 'music bars' (now) playing animation should be fixed as well. It is at least a lot more consistent, as well as the swipe to remove behavior.

**Closed** 2024-01-24 13:15 UTC
Labels: bug

**Comment by 25huizengek1** [comment] 2024-01-24 13:19
It should be fixed with this commit. Please let me know if any issues persist. This will at least be included in today's nightly build, but I'm thinking of releasing this tonight as well.

**Comment by ardumiguel** [comment] 2024-01-24 14:16
Can't really seem to find the release you are talking about... I do see like the commitments to main source.

Looking forward to trying out this version and giving feedback.

**Comment by 25huizengek1** [comment] 2024-01-24 15:03
It's not there yet. Every day at 22:00 CET (unless there is a reason that I skip the build for a day) a build is scheduled and released shortly after in my F-Droid repository, as 'ViMusic Nightly'. It's mainly for testing purposes, an actual release is available in GitHub releases and my F-Droid repository.

**Comment by ardumiguel** [comment] 2024-01-24 15:07
Ah, that makes more sense. Thanks dev I'll feedback ASAP. How do you prefer to receive feedback?

**Comment by genericbetatester** [comment] 2024-01-24 17:21
> Can't really seem to find the release you are talking about... I do see like the commitments to main source.
> 
> Looking forward to trying out this version and giving feedback.

I sent you an email, check it out

**Comment by genericbetatester** [comment] 2024-01-24 17:54
> > > Can't really seem to find the release you are talking about... I do see like the commitments to main source.
> > > Looking forward to trying out this version and giving feedback.
> > 
> > 
> > I sent you an email, check it out
> 
> I don't think you have my email 😅

I'm sorry 🙃😅 the message wasn't meant for you
