### ISSUE TITLE
Piped or Invidious Support Feature Request 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#2] opened 2023-11-12 20:15 UTC
### Steps to reproduce the bug

Would it be possible to support piped or invidious accounts and custom instances for library backups and then have your playlists cross-device? 

### Expected behavior

*

### Actual behavior

*

### ViMusic version

0.5.5

### Android version

Android 12

**Comment by 25huizengek1** [comment] 2023-11-12 21:31
Seems reasonable, but just to clarify, you meant a possibility to have Invidious or Piped accounts as a data source for playlists instead of the local database? Or do you want to synchronize specific playlists individually with Invidious or Piped?

Piped doesn't seem to have documentation for authenticated api endpoints, so I will have to look further into that.
I also do not know if YouTube Music in particular is (fully) supported by either platforms, so I have no idea if full custom instance support is possible.

**Comment by siggi1984** [comment] 2023-11-13 07:33
> Seems reasonable, but just to clarify, you meant a possibility to have Invidious or Piped accounts as a data source for playlists instead of the local database? Or do you want to synchronize specific playlists individually with Invidious or Piped?
> 
> Piped doesn't seem to have documentation for authenticated api endpoints, so I will have to look further into that. I also do not know if YouTube Music in particular is (fully) supported by either platforms, so I have no idea if full custom instance support is possible.

I don't necessarily mean Invidious or Piped as a music source.

Let me try to explain: I want to log in to my Piped or Invidious account to access my playlists but also the ability to edit playlists e.g.: create, delete etc.... ...

This developer has done it pretty well maybe you can just check it out.

https://github.com/anandnet/Harmony-Music

**Comment by 25huizengek1** [comment] 2023-11-13 22:58
Had a peek at the code, and it seems like it will be no problem to implement. There is one catch though: Piped doesn't seem to support reordering playlists, so while we could remove every out of order video and re-append everything when reordering, I think it is best to just disable reordering in Piped playlists. Even if we did it the hacky way, I think hitting rate-limits is just around the corner, considering they put a Cloudflare firewall in front of the API.

I'm going to start implementing this when I have the time to and I'll keep you updated.

**Comment by 25huizengek1** [comment] 2023-11-15 16:57
Haven't had much time to work on this because I kind of prioritized the smaller issues before, but I already coded the entire provider for the Piped API('s) and made the auth flow working in the UI. 

Still not entirely sure what strategy I should use for caching the data tho, should we just disallow mutating Piped playlists locally and always refetch from the server after a mutation? When we are offline for example we can't just use optimistic updates since rolling back (if needed) could lead to unexpected inconsistencies. 

Do you have any ideas on what you think works best for the user? @siggi1984

**Comment by siggi1984** [comment] 2023-11-15 17:36
> Haven't had much time to work on this because I kind of prioritized the smaller issues before, but I already coded the entire provider for the Piped API('s) and made the auth flow working in the UI.
> 
> Still not entirely sure what strategy I should use for caching the data tho, should we just disallow mutating Piped playlists locally and always refetch from the server after a mutation? When we are offline for example we can't just use optimistic updates since rolling back (if needed) could lead to unexpected inconsistencies.
> 
> Do you have any ideas on what you think works best for the user? @siggi1984

As I have absolutely no idea about programming, I'm afraid I can't help you here.

But this developer has added Piped in Seher streaming APP maybe it will help you?

https://github.com/anandnet/Harmony-Music

**Comment by 25huizengek1** [comment] 2023-11-15 18:00
No problem, I'll figure something out I guess.

I've installed their app and looked at their experience, they assume you are online when working with a Piped playlist, so if you don't have any connection the Piped playlists are just not visible. They seem to reload the playlist every time you try to access it, so if you lose connection while using the app, Piped playlists may end up looking 'empty' while really you are just offline.

Of course I could implement something similar in Kotlin and add it to ViMusic. The only problem I had is I wanted to implement support for offline caching of the playlists and I'm not sure what strategy to achieve that is best. For now I'll just implement it without offline support.

**Comment by 25huizengek1** [comment] 2023-11-15 18:29
Forgot to send the screenshots of the progress.

<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/f61ad7e7-c4c6-422a-8de4-7a3899e1b41a" width="30%" />
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/e85b9461-f46e-4e47-9add-eae95d87f844" width="30%" />
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/e9f7c850-d737-4b50-b777-fa8763a7ee17" width="30%" />

**Comment by siggi1984** [comment] 2023-11-15 18:36
> Forgot to send the screenshots of the progress.
> <img alt="" width="30%" src="https://user-images.githubusercontent.com/50515369/283212633-f61ad7e7-c4c6-422a-8de4-7a3899e1b41a.jpg"> <img alt="" width="30%" src="https://user-images.githubusercontent.com/50515369/283212637-e85b9461-f46e-4e47-9add-eae95d87f844.jpg"> <img alt="" width="30%" src="https://user-images.githubusercontent.com/50515369/283212640-e9f7c850-d737-4b50-b777-fa8763a7ee17.jpg">

Looks good and promising.

**Comment by 25huizengek1** [comment] 2023-11-19 23:45
Pushed my recent progress (058660e4afe366736ef97d62e78bec753f9b5d5b), gotta see if I can fit finishing Piped this week in my schedule tough.

**Comment by siggi1984** [comment] 2023-12-10 14:24
I'm cautiously asking if you can give me an update on the function and whether it might be included in the next version. I'm really excited and looking forward to the function.

**Comment by 25huizengek1** [comment] 2023-12-10 15:15
My apologies, this has been kind of a low priority for me. I've just merged all of the new changes with the piped feature branch, so the current state of the piped feature should be fully compatible with the newest changes now. I'll work on this when I have the time to.

**Comment by 25huizengek1** [comment] 2023-12-10 16:52
Status update: just worked on it and the feature is technically finished, still needs a bit of polish but I think we can merge, and it will be an experimental feature in nightly.

**Comment by 25huizengek1** [comment] 2023-12-11 21:05
I'm sorry, but due to partial outage on Piped's end and Cloudflare proxying I wasn't able to fix all issues with Piped. Probably going to merge all changes into master in one or two days...

**Closed** 2023-12-12 13:16 UTC
Labels: enhancement, in progress

**Comment by siggi1984** [comment] 2023-12-12 17:21
The app crashes as soon as you log in to Piped.

**Comment by 25huizengek1** [comment] 2023-12-12 22:34
What instance are you using? And can you please provide logs of the issue? Can't reproduce, didn't even get any crash during development.

**Comment by siggi1984** [comment] 2023-12-13 05:29
I use kavin.rocks. 

Unfortunately I have no idea how to create these logs.

At the moment I can't even select an instance. See video.

My device: Samsung Galaxy a21s, Android 12.


https://github.com/25huizengek1/ViMusic/assets/103368536/65a40479-7a60-4d6a-a1a5-2fc1c6f92781

**Comment by Enigma1309** [comment] 2023-12-13 05:50
This is quite off topic but how do i get access to nightly builds, i see nothing like nightly in releases 😓

**Comment by devika15** [comment] 2023-12-13 05:53
You can download it from Fdroid. Separate app called Vimusic Nightly.

**Comment by Enigma1309** [comment] 2023-12-13 06:02
> You can download it from Fdroid. Separate app called Vimusic Nightly.

Thankyou 🙌

**Comment by 25huizengek1** [comment] 2023-12-13 15:58
Moved to a new issue @siggi1984
