### ISSUE TITLE
Improper album art scaling on expanded player notification 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#60] opened 2024-01-03 17:36 UTC
### Steps to reproduce the bug

1. Expand player notification 

### Expected behavior

1. When the player notification is expanded, normally it should zoom in on the album art while preserving the album art position.

### Actual behavior

1. instead, the album art zooms in and offsets to the right hand side thereby cutting off the right side of the album art.

### Screenshots/Screen recordings

![Screenshot_20240103-182803](https://github.com/25huizengek1/ViMusic/assets/140274753/edbefca9-a029-4641-99ad-71607874697d)
![Screenshot_20240103-182742](https://github.com/25huizengek1/ViMusic/assets/140274753/7ba04552-3268-4bbc-b7bd-0564c9a647eb)
![Screenshot_20240103-182611](https://github.com/25huizengek1/ViMusic/assets/140274753/1384976f-bd95-412c-9385-b172cfd693aa)

### ViMusic version

V.0.6.2

### Android version

Android 10

### Additional information

It's quite minor but I think you might want to fix it

**Comment by 25huizengek1** [comment] 2024-01-03 21:37
Not a bug, removed that tag.

**Comment by 25huizengek1** [comment] 2024-01-03 21:39
I unfortunately do not have a lot of control on the layout/behavior of the notification, so I cannot fix/change this. The player notification looks different on every device/OEM. Closing this because of that, although I'm sorry for the inconvenience.

**Closed by 25huizengek1** 2024-01-03 21:39 UTC
Labels: enhancement

**Comment by genericbetatester** [comment] 2024-01-04 06:52
> I unfortunately do not have a lot of control on the layout/behavior of the notification, so I cannot fix/change this. The player notification looks different on every device/OEM. Closing this because of that, although I'm sorry for the inconvenience.

It's alright
