### ISSUE TITLE
Visual glitch observed with buttons on player screen

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#64] opened 2024-01-07 12:35 UTC
### Steps to reproduce the bug

1. It's really simple, just play a song

### Expected behavior

It should work fine

### Actual behavior

But the favorite, prev and next button flicker very quickly 

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/140274753/cc30bd4e-adb3-41aa-8c4d-82cd1c0e66dc

### ViMusic version

V.0.6.2

### Android version

Android 10

### Additional information

It happens randomly and works normally after sometimes again

**Comment by 25huizengek1** [comment] 2024-01-07 14:56
Can't reproduce. Any information about the device you're on? Or can you please provide some logs?

**Comment by genericbetatester** [comment] 2024-01-07 15:06
> Can't reproduce. Any information about the device you're on? Or can you please provide some logs?

I can't get a log but here is my device name: Tecno spark 6 go
Running Android 10

**Comment by 25huizengek1** [comment] 2024-01-07 18:32
Tested it on Android 10, without success. According to [this page](https://www.gsmarena.com/tecno_spark_6_go-10636.php) this page you're running Android Go, correct?

**Comment by genericbetatester** [comment] 2024-01-07 23:25
> Tested it on Android 10, without success. According to [this page](https://www.gsmarena.com/tecno_spark_6_go-10636.php) this page you're running Android Go, correct?

Yep, that's correct

**Comment by 25huizengek1** [comment] 2024-01-08 01:05
Well, that unfortunately means I don't know what could cause this issue. It may be a hardware problem, but there is no way for me to test this. There are no emulators for Android Go as of right now, so that is not something I could test against, as I do not own a device running Android Go.

While investigating further I'm pretty much certain that the buttons (tested on *stock* Android 10) don't even rerender at all, at least according to the Profiler, and Layout Inspector (no recompositions). The screen does not even draw anything while the player is idle.

There is still hope though. Android Go is meant for reducing the usage of system resources, memory for example. According to [the docs](https://developer.android.com/guide/topics/androidgo) Android Go 10 should be able to run on a system with only 512MB, which is an insanely low amount (at least these days). This design expects apps to do the same (at least on these systems): reduce memory usage as much as possible. That's also why they highly recommend [implementing memory-saving solutions](https://developer.android.com/guide/topics/androidgo/test#testing-reqs) on these versions. What I'm trying to say is that the system expects apps to account for this low-memory 'environment' and it may forcefully try to reduce memory usage whenever the app exceeds these expectations, or when the system is simply out of memory.

What I think though, is that while running ViMusic, listening to a song, the amount of system memory left already becomes really tight as the multi-threaded fetching, decoding and playing of music is kind of expensive. This could lead to the system trying to 'survive', while lagging the rendering of the UI. This is of course all hypothetical, but it's currently the only thing that comes to mind. Think of it as a video game performing worse when you have other apps in the background.

I do not know if this is possible on Android Go, but it's still worth giving a shot. To verify that this is indeed the case, as described above, I think this should be reflected in the app's logs. To get logs, you can of course hook up your device to a desktop and use `adb logcat`. If you don't know how this works, there is an alternative: you can record logs using a logger app like [this one](https://github.com/F0x1d/LogFox) and filter for ViMusic's logs. This app works on rooted devices, or using [Shizuku](https://shizuku.rikka.app/).

**Comment by 25huizengek1** [comment] 2024-01-08 01:15
Also, I just cleaned up (31f89df656ed41b4cd4bc658703db42214effb76) some stuff, improving Compose performance, so maybe it helps for you to try this on [the latest nightly build](https://github.com/25huizengek1/fdroid-repo/raw/master/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240107.apk) as it includes this fix. Don't worry though, Android sees this build as a separate app, so you can install this version next to your original ViMusic build.

**Comment by genericbetatester** [comment] 2024-01-08 11:56
I want to start by saying that I appreciate your work on this and your willingness to investigate the issue. I've read through your explanation, However,  I'm not too familiar with the technical details of your explanation, I will try to get the log as you said and I'll it get back to you as soon as possible. Also, I have to use the nightly build for sometimes before I can give a feedback, because the glitch happens randomly.

**Comment by 25huizengek1** [comment] 2024-01-08 15:34
No problem. Just keep the logging service running. If the issue occurs on either of them, just filter for logs of that build and share them in here.

**Comment by genericbetatester** [comment] 2024-01-08 16:03
> No problem. Just keep the logging service running. If the issue occurs on either of them, just filter for logs of that build and share them in here.

Alright. You haven't responded to the message I left on the discussion thread

**Comment by genericbetatester** [comment] 2024-01-12 10:39
@25huizengek1 I got the log. I captured it on the vimusic nightly build 0.6.2. I hadn't faced the issue since the last time that was why it took this long to provide the log. It happened just briefly 
[12_01-11-16-25_355.log.zip](https://github.com/25huizengek1/ViMusic/files/13917962/12_01-11-16-25_355.log.zip)

**Comment by 25huizengek1** [comment] 2024-01-12 23:10
While conducting a quick search, I unfortunately couldn't find much. There are a few warnings about performance but they do not seem significant. In the last few lines there is also an unrelated exception.

Can you please estimate when in the logs it happened? It covers a time span of 3 minutes or so and I think I can search more in-depth if I know this.

**Comment by genericbetatester** [comment] 2024-01-13 05:39
> While conducting a quick search, I unfortunately couldn't find much. There are a few warnings about performance but they do not seem significant. In the last few lines there is also an unrelated exception.
> 
> Can you please estimate when in the logs it happened? It covers a time span of 3 minutes or so and I think I can search more in-depth if I know this.

I started recording the logs immediately I noticed the glitch

**Comment by 25huizengek1** [comment] 2024-01-14 23:35
Logs AFTER the glitches are not always useful I'm afraid. If you do notice any UI jank in the future, please let me know.

As I said there are some performance warnings, so maybe that is just the problem. I also fixed a huge performance issue in my latest commit, so that may fix some of your problems.

**Comment by genericbetatester** [comment] 2024-01-15 04:22
> Logs AFTER the glitches are not always useful I'm afraid. If you do notice any UI jank in the future, please let me know.
> 
> As I said there are some performance warnings, so maybe that is just the problem. I also fixed a huge performance issue in my latest commit, so that might fix some of your problems.

That sounds great, thanks for the update! I’ll be sure to let you know if I notice anything else. It’s really helpful to know that you’re actively working to make the app better.

**Comment by 25huizengek1** [comment] 2024-01-17 15:12
No problem. Have you had any issues with this in the last couple, or can we close this for now?

**Comment by genericbetatester** [comment] 2024-01-17 16:02
> No problem. Have you had any issues with this in the last couple, or can we close this for now?

I haven't had any issue with it, you can close it

**Comment by 25huizengek1** [comment] 2024-01-17 16:04
Alright, please let me know and reopen when you do have issues again.

**Closed by 25huizengek1** 2024-01-17 16:04 UTC
Labels: bug
